version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bananaapi
      MYSQL_USER: bananaapi
      MYSQL_PASSWORD: password1234
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
        - ./:/var/www
    ports:
        - "9215:80"
    links:
        - app

  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
        - ./:/var/www
    links:
        - db

