-- MySQL Script generated by MySQL Workbench
-- 09/05/15 17:28:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banana` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `banana` ;

-- -----------------------------------------------------
-- Table `banana`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`media` ;

CREATE TABLE IF NOT EXISTS `banana`.`media` (
  `media_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `type` VARCHAR(15) NOT NULL DEFAULT 'image' COMMENT '',
  `mime` VARCHAR(45) NOT NULL COMMENT '',
  `width` TINYINT UNSIGNED NOT NULL COMMENT '',
  `height` TINYINT UNSIGNED NOT NULL COMMENT '',
  `hash` VARCHAR(35) NOT NULL COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`media_id`)  COMMENT '',
  INDEX `fk_media_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_media_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`users` ;

CREATE TABLE IF NOT EXISTS `banana`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `media_id` INT UNSIGNED NULL COMMENT '',
  `login` VARCHAR(25) NOT NULL COMMENT '',
  `password` VARCHAR(155) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  `date_validated_email` DATETIME NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_users_media1_idx` (`media_id` ASC)  COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  CONSTRAINT `fk_users_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `banana`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`quiz_has_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`quiz_has_stats` ;

CREATE TABLE IF NOT EXISTS `banana`.`quiz_has_stats` (
  `quiz_has_stats_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `quiz_id` INT UNSIGNED NOT NULL COMMENT '',
  `participations` INT UNSIGNED NOT NULL COMMENT '',
  `views` INT UNSIGNED NOT NULL COMMENT '',
  `likes` INT UNSIGNED NOT NULL COMMENT '',
  `shares` INT UNSIGNED NOT NULL COMMENT '',
  `comments` INT UNSIGNED NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`quiz_has_stats_id`)  COMMENT '',
  INDEX `fk_questions_quiz1_idx` (`quiz_id` ASC)  COMMENT '',
  CONSTRAINT `fk_questions_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `banana`.`quizzes` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`quizzes` ;

CREATE TABLE IF NOT EXISTS `banana`.`quizzes` (
  `quiz_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `media_id` INT UNSIGNED NOT NULL COMMENT '',
  `type` VARCHAR(20) NOT NULL DEFAULT 'classic' COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `state_visibility` TINYINT NULL DEFAULT 0 COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`quiz_id`)  COMMENT '',
  INDEX `fk_quizzes_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_quizzes_media1_idx` (`media_id` ASC)  COMMENT '',
  CONSTRAINT `fk_quizzes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quizzes_quiz_has_stats1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `banana`.`quiz_has_stats` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quizzes_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `banana`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`questions` ;

CREATE TABLE IF NOT EXISTS `banana`.`questions` (
  `question_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `quiz_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `media_id` INT UNSIGNED NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `state_order` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`question_id`)  COMMENT '',
  INDEX `fk_questions_quizzes_idx` (`quiz_id` ASC)  COMMENT '',
  INDEX `fk_questions_media1_idx` (`media_id` ASC)  COMMENT '',
  INDEX `fk_questions_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_questions_quizzes`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `banana`.`quizzes` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `banana`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`answers` ;

CREATE TABLE IF NOT EXISTS `banana`.`answers` (
  `answer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `question_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `media_id` INT UNSIGNED NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `is_right` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `state_order` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`answer_id`)  COMMENT '',
  INDEX `fk_answers_questions1_idx` (`question_id` ASC)  COMMENT '',
  INDEX `fk_answers_media1_idx` (`media_id` ASC)  COMMENT '',
  INDEX `fk_answers_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `banana`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `banana`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`results` ;

CREATE TABLE IF NOT EXISTS `banana`.`results` (
  `result_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `quiz_id` INT UNSIGNED NOT NULL COMMENT '',
  `media_id` INT UNSIGNED NULL COMMENT '',
  `type` VARCHAR(3) NOT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`result_id`)  COMMENT '',
  INDEX `fk_results_quizzes1_idx` (`quiz_id` ASC)  COMMENT '',
  INDEX `fk_results_media1_idx` (`media_id` ASC)  COMMENT '',
  CONSTRAINT `fk_results_quizzes1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `banana`.`quizzes` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `banana`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`quiz_has_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`quiz_has_like` ;

CREATE TABLE IF NOT EXISTS `banana`.`quiz_has_like` (
  `like_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `quiz_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`like_id`)  COMMENT '',
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `type_id_UNIQUE` (`quiz_id` ASC)  COMMENT '',
  CONSTRAINT `fk_like_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_has_like_quizzes1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `banana`.`quizzes` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`user_oauth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`user_oauth` ;

CREATE TABLE IF NOT EXISTS `banana`.`user_oauth` (
  `user_oauth_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `type` VARCHAR(25) NOT NULL COMMENT '',
  `type_user_id` VARCHAR(25) NOT NULL COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  `date_updated` DATETIME NOT NULL COMMENT '',
  `date_deleted` DATETIME NULL COMMENT '',
  PRIMARY KEY (`user_oauth_id`)  COMMENT '',
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `type_UNIQUE` (`type` ASC)  COMMENT '',
  CONSTRAINT `fk_user_oauth_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banana`.`quiz_has_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banana`.`quiz_has_history` ;

CREATE TABLE IF NOT EXISTS `banana`.`quiz_has_history` (
  `history_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NULL COMMENT '',
  `quiz_id` INT UNSIGNED NOT NULL COMMENT '',
  `result_id` INT UNSIGNED NOT NULL COMMENT '',
  `date_created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`history_id`)  COMMENT '',
  INDEX `fk_quiz_has_history_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_quiz_has_history_quizzes1_idx` (`quiz_id` ASC)  COMMENT '',
  INDEX `fk_quiz_has_history_results1_idx` (`result_id` ASC)  COMMENT '',
  CONSTRAINT `fk_quiz_has_history_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banana`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_has_history_quizzes1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `banana`.`quizzes` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_has_history_results1`
    FOREIGN KEY (`result_id`)
    REFERENCES `banana`.`results` (`result_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
