---
- name: installation des serveur
  hosts: all
  remote_user: root

  tasks:
    - name: Add stretch apt repositories
      apt_repository:
        repo: "deb http://ftp2.fr.debian.org/debian/ stretch main non-free contrib"
        state: present

    - name: Add stretch apt src repositories
      apt_repository:
        repo: "deb-src http://ftp2.fr.debian.org/debian/ stretch main non-free contrib"
        state: present


    - name: Install basic
      apt: name={{ item }}
      with_items:
        - git
        - htop
        - screen
        - emacs
        - curl


    - name: install banana requirement
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - mysql-client
        - mysql-common
        - php7.0
        - php7.0-common
        - php7.0-fpm
        - php7.0-opcache
        - php7.0-mysql
        - php7.0-json
        - php7.0-mcrypt
        - php7.0-xml
        - php7.0-mbstring
        - php7.0-curl
        - phpmd
        - phpunit
        - python-mysqldb
      notify:
        - restart php


    - name: install banana composer
      composer:
        command: install
        working_dir: /home/banana-api/

    - name: install database
      mysql_db:
        name: banana
        state: present

    - name: create user for mysql_db
      mysql_user:
        name: bananauser
        password: bananauser123
        priv: 'banana.*:ALL'
        state: present

    - name: create schema
      shell: php /home/banana-api/artisan migrate --force

    - name: seed db
      shell: php /home/banana-api/artisan db:seed --force

  handlers:
    - name: restart php
      service: name=php7.0-fpm state=restarted

